# Generated by Django 5.0.6 on 2024-05-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('first_season_year', models.IntegerField()),
                ('last_season_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('weeks_scheduled', models.IntegerField()),
                ('weeks_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('average_points', models.DecimalField(decimal_places=14, default=0, max_digits=16)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_seasons.league')),
                ('season_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_seasons.season')),
            ],
        ),
    ]
